/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: ../shared/schema.json
export type DisputeReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "dispute";
};

export type ClaimReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "claim";
};

export type Ruling = {
  _id: string;
  _type: "ruling";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  dispute?: DisputeReference;
  outcome?: "keep" | "split" | "retire";
  resultingClaims?: Array<
    {
      _key: string;
    } & ClaimReference
  >;
  summary?: string;
  moderator?: string;
};

export type AttesterReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "attester";
};

export type Dispute = {
  _id: string;
  _type: "dispute";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  claim?: ClaimReference;
  reason?: string;
  evidence?: Array<{
    url?: string;
    note?: string;
    _type: "evidenceItem";
    _key: string;
  }>;
  openedBy?: AttesterReference;
};

export type Attestation = {
  _id: string;
  _type: "attestation";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  claim?: ClaimReference;
  stance?: "rude" | "fine" | "depends";
  confidence?: 1 | 2 | 3;
  locality?: "local" | "lived-there" | "visitor";
  note?: string;
  attester?: AttesterReference;
  source?: "web" | "seed" | "studio";
};

export type PlaceReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "place";
};

export type ContextReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "context";
};

export type Claim = {
  _id: string;
  _type: "claim";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  statement?: string;
  slug?: Slug;
  place?: PlaceReference;
  context?: ContextReference;
  parent?: ClaimReference;
  detail?: string;
  proposedBy?: AttesterReference;
  dedupe?: {
    status?: "pending" | "unique" | "possible-duplicate" | "merged";
    checkedAt?: string;
    notes?: string;
    related?: Array<
      {
        _key: string;
      } & ClaimReference
    >;
  };
};

export type Attester = {
  _id: string;
  _type: "attester";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  handle?: string;
  homePlaces?: Array<
    {
      _key: string;
    } & PlaceReference
  >;
  key?: string;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Context = {
  _id: string;
  _type: "context";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  icon?: string;
};

export type Place = {
  _id: string;
  _type: "place";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  kind?: "country" | "region" | "city";
  parent?: PlaceReference;
  iso?: string;
  flag?: string;
  blurb?: string;
};

export type WorkflowDefinition = {
  _id: string;
  _type: "workflow.definition";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  documentType?: string;
  description?: string;
  forwardOnly?: boolean;
  roles?: Array<
    {
      _key: string;
    } & WorkflowRole
  >;
  stages?: Array<
    {
      _key: string;
    } & WorkflowStage
  >;
  offRamps?: Array<
    {
      _key: string;
    } & WorkflowOffRamp
  >;
};

export type WorkflowAssignment = {
  _type: "workflow.assignment";
  assignmentType?: string;
  userId?: string;
};

export type WorkflowOffRamp = {
  _type: "workflow.offRamp";
  label?: string;
  slug?: Slug;
  icon?: WorkflowLucideIcon;
  tone?: "caution" | "critical";
  stageCriteria?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  enablePublishing?: boolean;
  unpublishOnEntry?: boolean;
  allowedRoles?: Array<string>;
  enableNotifications?: boolean;
  notifyUserTypes?: Array<string>;
};

export type WorkflowLucideIcon = string;

export type WorkflowStage = {
  _type: "workflow.stage";
  label?: string;
  slug?: Slug;
  icon?: WorkflowLucideIcon;
  color?: WorkflowColor;
  stageCriteria?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  taskTemplates?: Array<
    {
      _key: string;
    } & WorkflowTaskTemplate
  >;
  enableCompletionGating?: boolean;
  gatingOverrideRoles?: Array<string>;
  enablePublishing?: boolean;
  enableNotifications?: boolean;
  notifyUserTypes?: Array<string>;
};

export type WorkflowColor = {
  _type: "workflow.color";
  hex?: string;
  alpha?: number;
  hsl?: HslaColor;
  hsv?: HsvaColor;
  rgb?: RgbaColor;
};

export type WorkflowTaskTemplate = {
  _type: "workflow.taskTemplate";
  title?: string;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  assigneeRole?: string;
  dueInDays?: number;
  required?: boolean;
};

export type WorkflowRole = {
  _type: "workflow.role";
  label?: string;
  slug?: Slug;
  description?: string;
  projectRoles?: Array<string>;
};

export type WorkflowSetStatus = {
  _type: "workflow.setStatus";
  statusLabel?: string;
  statusSlug?: string;
  statusIcon?: string;
  completedAt?: string;
  completedBy?: WorkflowUser;
  reason?: string;
};

export type WorkflowUser = {
  _type: "workflow.user";
  userId?: string;
};

export type RgbaColor = {
  _type: "rgbaColor";
  r?: number;
  g?: number;
  b?: number;
  a?: number;
};

export type HsvaColor = {
  _type: "hsvaColor";
  h?: number;
  s?: number;
  v?: number;
  a?: number;
};

export type HslaColor = {
  _type: "hslaColor";
  h?: number;
  s?: number;
  l?: number;
  a?: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | DisputeReference
  | ClaimReference
  | Ruling
  | AttesterReference
  | Dispute
  | Attestation
  | PlaceReference
  | ContextReference
  | Claim
  | Attester
  | Slug
  | Context
  | Place
  | WorkflowDefinition
  | WorkflowAssignment
  | WorkflowOffRamp
  | WorkflowLucideIcon
  | WorkflowStage
  | WorkflowColor
  | WorkflowTaskTemplate
  | WorkflowRole
  | WorkflowSetStatus
  | WorkflowUser
  | RgbaColor
  | HsvaColor
  | HslaColor
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityImageHotspot
  | SanityImageCrop
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;
